//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2.Disaster.CoreEntities.Domain.GeoDisaster.Emergency
{
    using R2.Disaster.CoreEntities.Domain.GeoDisaster.Investigation;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 灾情速报实体
    /// </summary>
    public partial class DamageReport:PhyRelationEntity
    {
        public virtual PhyGeoDisaster PhyGeoDisaster { get; set; }

        //public int Id { get; set; }
        public string 灾险情地点 { get; set; }
        public DateTime 发生时间 { get; set; }
        public EnumGeoDisasterType 灾害类型 { get; set; }
        public string 灾害等级 { get; set; }
        public string 灾害规模 { get; set; }
        public int 死亡 { get; set; }
        public int 失踪 { get; set; }
        public int 受伤 { get; set; }
        public double 直接经济损失 { get; set; }
        public string 地理位置 { get; set; }
        public string 接报时间 { get; set; }
        public string 主要诱发因素 { get; set; }
        public string 威胁对象范围 { get; set; }
        public string 地质成因 { get; set; }
        public string 发展趋势 { get; set; }
        public string 已采取的应急措施 { get; set; }
        public string 防治建议 { get; set; }
        public string 县政府 { get; set; }
        public string 县政府联系人 { get; set; }
        public string 县国土资源局 { get; set; }
        public string 县国土资源局联系人 { get; set; }
        public string 乡政府 { get; set; }
        public string 乡政府联系人 { get; set; }
        public string 县区 { get; set; }
        public string 乡镇 { get; set; }
        public string 村 { get; set; }
        public string 组 { get; set; }
    }
}
